# Generated by Django 5.2.8 on 2025-11-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('tipo_sangre', models.CharField(max_length=5)),
                ('direccion', models.TextField()),
                ('imagen', models.ImageField(upload_to='docentes/')),
            ],
        ),
    ]
