# Generated by Django 5.2.8 on 2025-11-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_creditos', models.IntegerField()),
                ('nivel', models.CharField(max_length=20)),
                ('horas_semana', models.IntegerField()),
                ('jornada', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='materias/')),
                ('docentes', models.ManyToManyField(related_name='materias', to='docentes.docente')),
            ],
        ),
    ]
